export const TOGGLE_STEP = 'TOGGLE_STEP';
export const INCREMENT_LAST_COLUMN = 'INCREMENT_LAST_COLUMN';
export const DECREMENT_LAST_COLUMN = 'DECREMENT_LAST_COLUMN';
export const NEXT_INSTRUMENT_TICK = 'NEXT_INSTRUMENT_TICK';
export const CHANGE_PALETTE = 'CHANGE_PALETTE';
export const INCREMENT_NOTE = 'INCREMENT_NOTE_NAME';
export const DECREMENT_NOTE = 'DECREMENT_NOTE_NAME';
export const TOGGLE_PLAY = 'TOGGLE_PLAY';
